
#ifndef GLOBALS_H
#define GLOBALS_H

#define PERIPHERAL_BASE 0xFE000000

#define SCREENWIDTH 1920
#define SCREENHEIGHT 1080
#define VIRTUAL_SCREENWIDTH 1920 
#define VIRTUAL_SCREENHEIGHT SCREENHEIGHT*2
#define DEPTH 32

#endif

