
#ifndef GLOBALS_H
#define GLOBALS_H

#define PERIPHERAL_BASE 0xFE000000

#define SCREENWIDTH 640
#define SCREENHEIGHT 480
#define VIRTUAL_SCREENWIDTH SCREENWIDTH
#define VIRTUAL_SCREENHEIGHT SCREENHEIGHT*2
#define DEPTH 32

#endif

